name: Test
on: [push]
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      -
        name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Test
        run: make test
      -
        name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.0
        with:
          infile: coverage.out
          outfile: coverage.lcov
      -
        name: Coveralls
        uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
